{% set name = "pangolin" %}
{% set version = "master" %}
{% set commit = "ad8b5f83222291c51b4800d5a5873b0e90a0cf81" %}
{% set sha256 = "698c57baac13ecfbd39c533aaff9221549b29cae2688bb12eb7f66b3a50bf792" %}
{% set pybind_version = "stable" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/stevenlovegrove/Pangolin/archive/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - macros.patch
  - url: https://github.com/pybind/pybind11/archive/{{ pybind_version }}.tar.gz
    fn: pybind-{{ pybind_version }}.tar.gz
    sha256: 24c820c1bf501890564745cc078464726623b17ba43b4bb38be93045281b7052
    folder: external/pybind11

build:
  number: 1

requirements:
  build:
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
    - cmake
    # - ninja
    - pkg-config
  host:
    - eigen {{ eigen }}
    - suitesparse {{ suitesparse }}
    - ffmpeg
    - freeglut
    - libtiff
    - zlib
    - lz4
    - python
    - glew

about:
  home: https://github.com/stevenlovegrove/Pangolin
  summary: Pangolin is a lightweight portable rapid development library for managing OpenGL display / interaction and abstracting video input
  license: MIT

extra:
  recipe-maintainers:
  - v-turin
